[build-system]
requires = [
    'setuptools ~= 82.0',
]
build-backend = 'setuptools.build_meta'

[project]
version = '0.0.0'
name = 'betty_nginx'
description = 'Nginx for Betty provides nginx and Docker integration for your Betty sites'
readme = 'README.md'
license = {file = 'LICENSE.txt'}
authors = [
  {name = 'Bart Feenstra', email = 'bar@bartfeenstra.com'},
]
requires-python = '~= 3.13'
dependencies = [
    'betty == 0.5.0a41',
    'docker ~= 7.1',
]
classifiers = [
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Intended Audience :: End Users/Desktop',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Programming Language :: Lua',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Programming Language :: Unix Shell',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: POSIX :: Linux',
    'Operating System :: Microsoft :: Windows',
    'Topic :: Internet',
    'Topic :: Scientific/Engineering :: Visualization',
    'Topic :: Sociology :: Genealogy',
    'Topic :: Sociology :: History',
    'Topic :: Software Development :: Code Generators',
    'Natural Language :: Dutch',
    'Natural Language :: English',
    'Natural Language :: French',
    'Natural Language :: German',
    'Natural Language :: Ukrainian',
    'Typing :: Typed',
]

[project.urls]
Github = 'https://github.com/bartfeenstra/betty-nginx'

[project.entry-points.'betty.asset_directory']
'nginx' = 'betty_nginx.plugins.asset_directory.nginx:NGINX'

[project.entry-points.'betty.command']
'nginx-generate' = 'betty_nginx.plugins.command.nginx_generate:NginxGenerate'
'nginx-serve' = 'betty_nginx.plugins.command.nginx_serve:NginxServe'

[project.entry-points.'betty.extension']
'nginx' = 'betty_nginx.plugins.extension.nginx:Nginx'

[project.optional-dependencies]
setuptools = [
    'build ~= 1.3',
    'twine ~= 6.0',
    'wheel ~= 0.47',
]
test = [
    'aioresponses ~= 0.7.8',
    'coverage ~= 7.6',
    'lxml ~= 6.0',
    'pytest ~= 9.0',
    'pytest-asyncio ~= 1.2',
    'pytest-mock ~= 3.14',
    'requests ~= 2.32',
    'ruff ~= 0.8',
    'ty == 0.0.32',
    'types-lxml >= 2026.2.16',
    'types-requests ~= 2.32',
    'virtualenv ~= 21.3',
    'betty_nginx[setuptools]',
]
development = [
    'pytest-repeat ~= 0.9',
    'betty_nginx[test]',
]
ci = [
    'codecov ~= 2.1',
    'betty_nginx[test]',
]

[tool.setuptools.packages.find]
where = ['.']
exclude = [
    'betty_nginx.tests',
    'betty_nginx.tests.*',
]

[tool.setuptools.package-data]
betty_nginx = [
    'py.typed',

    # Assets.
    'assets/**',
    'extension/*/assets/**',
]

[tool.setuptools.exclude-package-data]
betty_nginx = [
    '__pycache__',
]
